### ISSUE TITLE
What is the difference between AMuLap and Auto-L + AMuLap in Table 2?

### ISSUE THREAD

**Issue by wjczf123** [HanNight/AMuLaP#1]
Nice work! I have a question about Table 2, What is the difference between AMuLap and Auto-L + AMuLap in Table 2?

**Comment by HanNight** [comment]
Hi,

Auto-L constructs a pruned set of label words using D_train and then determines the final mapping by **fine-tuning** on all of them and selecting the best with D_dev. Auto-L + AMuLap replaces the predicted token distribution of AMuLaP
with the validation score of all fine-tuned assignments and then uses AMuLap to select the label mapping.

AMuLap selects the label mapping **without fine-tuning**.

**Comment by wjczf123** [comment]
Thanks for your reply. I get it. 

Are you also use the demonstration sampling same as Gao et al. (2021)?

**Comment by HanNight** [comment]
We do not use the demonstration sampling.

**Comment by wjczf123** [comment]
OK. Thank you a lot.
